import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import type { Request, Response } from 'express';
import { User } from '../models/user.model';
import { sendEmail } from '../services/email.service';
import { hashToken, signToken } from '../utils/auth';

const userResponse = (user: any) => ({ id: user.id, fullName: user.fullName, email: user.email, phone: user.phone, faculty: user.faculty, department: user.department, semester: user.semester, gender: user.gender, role: user.role, profileComplete: Boolean(user.phone && user.faculty && user.department && user.semester && user.gender), profilePhoto: user.profilePhoto });
export async function register(request: Request, response: Response) { const { fullName, email, password, phone } = request.body; if (!fullName || !email || !phone || !password || password.length < 8) return response.status(400).json({ message: 'Name, email, phone number and a password of at least 8 characters are required' }); if (await User.exists({ email })) return response.status(409).json({ message: 'Email already registered' }); const user = await User.create({ fullName, email, phone, passwordHash: await bcrypt.hash(password, 12) }); void sendEmail({ userId: user.id, recipient: user.email, subject: 'Welcome to JUSA Events', title: `Welcome, ${user.fullName}!`, body: 'You can now discover upcoming seminars, reserve seats and manage your registrations online.', cta: { label: 'Explore Seminars', url: `${process.env.APP_URL || 'http://localhost:5173'}/seminars` } }); return response.status(201).json({ user: userResponse(user), token: signToken({ id: user.id, role: user.role }) }); }
export async function login(request: Request, response: Response) { const user = await User.findOne({ email: String(request.body.email || '').toLowerCase() }); if (!user?.passwordHash || !(await bcrypt.compare(request.body.password || '', user.passwordHash))) return response.status(401).json({ message: 'Invalid email or password' }); return response.json({ user: userResponse(user), token: signToken({ id: user.id, role: user.role }) }); }
export async function me(request: Request, response: Response) { const user = await User.findById(request.user!.id); return user ? response.json({ user: userResponse(user) }) : response.status(404).json({ message: 'User not found' }); }
export async function forgotPassword(request: Request, response: Response) { const user = await User.findOne({ email: String(request.body.email || '').toLowerCase() }); if (user) { const token = crypto.randomBytes(24).toString('hex'); user.resetTokenHash = hashToken(token); user.resetTokenExpiresAt = new Date(Date.now() + 60 * 60 * 1000); await user.save(); const url = `${process.env.APP_URL || 'http://localhost:5173'}/reset-password?token=${token}`; await sendEmail({ userId: user.id, recipient: user.email, subject: 'Reset your JUSA Events password', title: 'Reset your password', body: 'Use the secure link below to choose a new password. This link expires in one hour.', cta: { label: 'Reset password', url } }); } return response.json({ message: 'If that email exists, a password reset message has been sent.' }); }
export async function resetPassword(request: Request, response: Response) { const token = String(request.body.token || ''); const password = String(request.body.password || ''); if (password.length < 8) return response.status(400).json({ message: 'Password must be at least 8 characters' }); const user = await User.findOne({ resetTokenHash: hashToken(token), resetTokenExpiresAt: { $gt: new Date() } }); if (!user) return response.status(400).json({ message: 'Reset link is invalid or expired' }); user.passwordHash = await bcrypt.hash(password, 12); user.resetTokenHash = undefined; user.resetTokenExpiresAt = undefined; await user.save(); return response.json({ message: 'Password updated successfully' }); }
export function googleStart(request: Request, response: Response) { if (!process.env.GOOGLE_CLIENT_ID || !process.env.GOOGLE_CLIENT_SECRET || !process.env.GOOGLE_CALLBACK_URL) return response.status(503).json({ message: 'Google sign-in is not configured' }); const state = crypto.randomBytes(24).toString('hex'); response.cookie('jusa_oauth_state', state, { httpOnly: true, sameSite: 'lax', secure: process.env.NODE_ENV === 'production', maxAge: 600000 }); const params = new URLSearchParams({ client_id: process.env.GOOGLE_CLIENT_ID, redirect_uri: process.env.GOOGLE_CALLBACK_URL, response_type: 'code', scope: 'openid email profile', state, prompt: 'select_account' }); return response.redirect(`https://accounts.google.com/o/oauth2/v2/auth?${params}`); }
export async function googleCallback(request: Request, response: Response) { const appUrl = process.env.APP_URL || 'http://localhost:5173'; const fail = (message: string) => response.redirect(`${appUrl}/login?oauthError=${encodeURIComponent(message)}`); if (!request.query.code || !request.query.state || request.query.state !== request.cookies?.jusa_oauth_state) return fail('Google sign-in could not be verified. Please try again.'); response.clearCookie('jusa_oauth_state'); const tokenResponse = await fetch('https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ code: String(request.query.code), client_id: process.env.GOOGLE_CLIENT_ID || '', client_secret: process.env.GOOGLE_CLIENT_SECRET || '', redirect_uri: process.env.GOOGLE_CALLBACK_URL || '', grant_type: 'authorization_code' }) }); const tokens = await tokenResponse.json() as { access_token?: string }; if (!tokenResponse.ok || !tokens.access_token) return fail('Google sign-in failed. Please try again.'); const profileResponse = await fetch('https://www.googleapis.com/oauth2/v3/userinfo', { headers: { Authorization: `Bearer ${tokens.access_token}` } }); const profile = await profileResponse.json() as { sub?: string; email?: string; email_verified?: boolean; name?: string; picture?: string }; if (!profileResponse.ok || !profile.sub || !profile.email || !profile.email_verified) return fail('A verified Google email address is required.'); const googleEmail = profile.email.toLowerCase(); let user = await User.findOne({ $or: [{ googleId: profile.sub }, { email: googleEmail }] }); if (!user) { user = await User.create({ fullName: profile.name || googleEmail.split('@')[0], email: googleEmail, googleId: profile.sub, profilePhoto: profile.picture, authProvider: 'GOOGLE' }); void sendEmail({ userId: user.id, recipient: user.email, subject: 'Welcome to JUSA Events', title: `Welcome, ${user.fullName}!`, body: 'Your verified Google email is now connected. Complete your profile to start registering for seminars.' }); } else if (!user.googleId) { user.googleId = profile.sub; user.profilePhoto ||= profile.picture; user.authProvider = 'GOOGLE'; await user.save(); } const destination = `${appUrl}/oauth/callback?token=${encodeURIComponent(signToken({ id: user.id, role: user.role }))}`; return response.redirect(destination); }
