import type { Request, Response } from 'express';
import { Registration } from '../models/registration.model';
import { Seminar } from '../models/seminar.model';
import { User } from '../models/user.model';
import { cancelRegistration, getQrDataUrl, registerForSeminar } from '../services/registration.service';
import { sendEmail } from '../services/email.service';
export async function register(request: Request, response: Response) { const seminarId = String(request.params.id); const user = await User.findById(request.user!.id); if (!user?.fullName || !user.phone || !user.faculty || !user.department || !user.semester || !user.gender) return response.status(422).json({ message: 'Complete your name, phone, faculty, department, class and gender before registering' }); try { const { registration, waitlistPosition } = await registerForSeminar(seminarId, user.id); const seminar = await Seminar.findById(seminarId); void sendEmail({ userId: user.id, seminarId, recipient: user.email, subject: registration.status === 'REGISTERED' ? 'Your JUSA Seminar Registration is Confirmed' : 'You Have Joined the JUSA Seminar Waitlist', title: registration.status === 'REGISTERED' ? 'Your seat is reserved' : 'You are on the waitlist', body: registration.status === 'REGISTERED' ? `Your seat for <b>${seminar?.title}</b> has been successfully reserved. Please keep your QR pass ready.` : `You are #${waitlistPosition} on the waitlist for <b>${seminar?.title}</b>.` }); return response.status(201).json({ data: { ...(typeof registration.toJSON === 'function' ? registration.toJSON() : registration), id: registration.id, status: registration.status }, waitlistPosition }); } catch (error) { return response.status(409).json({ message: error instanceof Error ? error.message : 'Registration failed' }); } }
export async function cancel(request: Request, response: Response) { try { const result = await cancelRegistration(String(request.params.id), request.user!.id); return response.json({ message: 'Registration cancelled', ...result }); } catch (error) { return response.status(409).json({ message: error instanceof Error ? error.message : 'Cancellation failed' }); } }
export async function myEvents(request: Request, response: Response) { const data = await Registration.find({ userId: request.user!.id }).populate('seminarId').sort({ createdAt: -1 }); return response.json({ data }); }
export async function qrPass(request: Request, response: Response) { try { const data = await getQrDataUrl(String(request.params.id), request.user!.id); return response.json({ dataUrl: data.dataUrl, registration: data.registration, attendance: data.attendance }); } catch (error) { return response.status(404).json({ message: error instanceof Error ? error.message : 'QR unavailable' }); } }
